In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
img = cv2.imread("sample.jpg")
cv2.imshow("img", img)
cv2.waitKey(0)

-1

In [3]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


In [4]:
#template = cv2.imread('img1.jpeg',0)
template = cv2.imread('sample_2.jpg',0)
#template = cv2.imread('img3.jpeg',0)

cv2.imshow("template", template)
cv2.waitKey(0)
print (template)

[[254 254 254 ... 194 192 192]
 [254 254 254 ... 194 192 194]
 [254 254 254 ... 194 191 193]
 ...
 [255 255 255 ... 254 254 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [5]:
width, height = template.shape[::-1]
result = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED)
threshold = 0.8
loc = np.where( result >= threshold)
for point in zip(*loc[::-1]):
    cv2.rectangle(img, point, (point[0] + width, point[1] + height), (0,255,0), 1)
    
cv2.imshow('res.jpg',img)
cv2.waitKey(0)

-1

In [6]:
g = cv2.imread("Sample.jpg")

In [7]:
cv2.imshow('sample.jpg',g)
cv2.waitKey(0)

-1

In [8]:
dim = (1080,720)

In [9]:
f = cv2.resize(g,dim,interpolation = cv2.INTER_AREA)

In [10]:
cv2.imshow('sample.jpg',f)
cv2.waitKey(0)

-1

In [11]:
cv2.imwrite('sample.jpg',f)

True